name: Packer

on:
  push:
    branches: [main]
  pull_request:
    # Run checks on reopened draft PRs to support triggering PR checks on draft PRs that were opened
    # by other workflows.
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  packer:
    defaults:
      run:
        shell: bash
        working-directory: rocky9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Install pre-reqs
        run: sudo apt-get install libnbd-bin nbdkit fuse2fs -y

      - name: Make
        run: packer init rocky9.pkr.hcl

      - uses: hashicorp/packer-github-actions@master
        with:
          command: fmt
          arguments: -check -diff
          target: .

      - name: Find qemu
        run: |
          find | grep '/bin/'

      - name: Make
        run: make
