name: Packer

on:
  push:
    branches: [main]
  pull_request:
    # Run checks on reopened draft PRs to support triggering PR checks on draft PRs that were opened
    # by other workflows.
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  packer:
    defaults:
      run:
        shell: bash
        working-directory: ./rocky9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/packer-github-actions@master
        with:
          command: fmt
          arguments: -check -diff
          target: .
      - uses: hashicorp/packer-github-actions@master
        with:
          command: init
          arguments: rocky9.pkr.hcl
      - uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: -var timeout=1h rocky9.pkr.hcl
